from core.interfaceRepositories.project_irepository import IProjectRepository
from core.interfaceRepositories.task_irepository import ITaskRepository
from core.interfaceRepositories.event_ipublisher import IEventPublisher
